# Exclude every file or folder starting with a dot.
exclude: ^\.
repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.7.0
    hooks:
    -   id: reorder-python-imports
        files: '(\.pyi?|wscript)$'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=100000']  # Set to max file size in Github
    -   id: check-byte-order-marker
        types: [text]
    -   id: check-merge-conflict
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.24.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
        files: '(\.pyi?|wscript)$'
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        files: '(\.md|\.rst)$'
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        files: '(\.pyi?|wscript)$'
        language_version: python3.7

